[log]
setLogcallers = true
outputLevel = "info" # debug, info, warn, error, fatal, none

[datahub]
address = "datahub.alameda.svc.cluster.local:50050"

[eviction]
checkCycle = 3 # second
enable = false
purgeContainerCpuMemory = false

[admissionController]
serviceName = "admission-controller"
servicePort = 443
