# CA certificate file to provide in k8s object MutatingWebhookConfiguration
caCertFile = ""

# The ssl certificate file to use to run HTTPS server.
tlsCertFile = ""

# The ssl key file to use to run HTTPS server.
tlsPrivateKeyFile = ""

# Determines whether admission-controller is enabled.
enable = false

# Specified which namespace did the admission-controller deployed on. 
deployedNamespace = "alameda"

# Option of json patch validation function, empty value may use default function which won't do any validation.
jsonPatchValidationFunc = "" # openshift3.9

port = 8000

[log]
setLogcallers = true
outputLevel = "info" # debug, info, warn, error, fatal, none

[datahub]
address = "datahub.alameda.svc:50050"

[service]
name = "admission-controller"
port = 443

[gRPC]
retry = 4
